### ISSUE TITLE
showUserPostition={true} crash

### ISSUE THREAD

**Issue by Robgen49** [volga-volga/react-native-yamap#281]
вылетает, если не заюзать false(
"react-native-yamap": "^4.1.18",
"react-native": "0.68.0"

                                                                                                    FATAL EXCEPTION: main
                                                                                                    Process: com.alyans_auto, PID: 8257
                                                                                                    java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~aJu-kzKnhm47BwanAdGoyA==/com.alyans_auto-FNJQ5w4CSMxIg7SU2uZQMg==/base.apk!classes8.dex)
                                                                                                    	at com.yandex.runtime.sensors.internal.FusedLocationSubscription.onConnected(FusedLocationSubscription.java:71)
                                                                                                    	at com.google.android.gms.common.internal.zak.zad(com.google.android.gms:play-services-base@@18.3.0:11)
                                                                                                    	at com.google.android.gms.common.api.internal.zabe.zab(com.google.android.gms:play-services-base@@18.3.0:3)
                                                                                                    	at com.google.android.gms.common.api.internal.zaaw.zaC(com.google.android.gms:play-services-base@@18.3.0:11)
                                                                                                    	at com.google.android.gms.common.api.internal.zaaw.zag(com.google.android.gms:play-services-base@@18.3.0:4)
                                                                                                    	at com.google.android.gms.common.api.internal.zabi.onConnected(com.google.android.gms:play-services-base@@18.3.0:2)
                                                                                                    	at com.google.android.gms.common.api.internal.zat.onConnected(com.google.android.gms:play-services-base@@18.3.0:1)
                                                                                                    	at com.google.android.gms.common.internal.zah.onConnected(com.google.android.gms:play-services-base@@18.3.0:1)
                                                                                                    	at com.google.android.gms.common.internal.zzf.zzd(com.google.android.gms:play-services-basement@@18.3.0:10)
                                                                                                    	at com.google.android.gms.common.internal.zza.zza(com.google.android.gms:play-services-basement@@18.3.0:1)
                                                                                                    	at com.google.android.gms.common.internal.zzc.zze(com.google.android.gms:play-services-basement@@18.3.0:3)
                                                                                                    	at com.google.android.gms.common.internal.zzb.handleMessage(com.google.android.gms:play-services-basement@@18.3.0:31)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7839)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by stasovlas** [comment]
надо сначала получить у пользователя разрешение на использование геопозиции
